name = "test-tinymce-editor"
main = "src/index.js"
compatibility_date = "2026-04-19"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "public"
binding = "ASSETS"

[vars]
CICEROLMS_EDITOR_LIB_URL = "https://raw.githubusercontent.com/cicerolms/customed_TinyMCE/main/dist/index.js"

[[d1_databases]]
binding = "DB"
database_name = "test_tinymce_db"
database_id = "3760b45a-1ca7-4be5-9df6-af5a82986c34"
